location: The Hague
avatar: assets/pro-pic-circular-musa.png
resume_pdf: /s/musa-resume-2026.pdf
bio:
  paragraphs:
    - Product designer based in {{location}}, interested in growth hacking & designOps
    - Currently designing at Nord Security. Previously, for **Vermietet.de (ImmoScout24)**.
    - Interested in open source & research projects. Feel free to say hello!
  highlights:
    - phrase: growth hacking
      style: underline
      bold: false
      href: ''
    - phrase: designOps
      style: scribble
      bold: true
      href: ''
    - phrase: Nord Security
      style: underline
      bold: true
      href: https://nordsecurity.com/
      color: white
    - phrase: say hello
      style: underline
      bold: false
      href: https://adplist.org/mentors/musavvir-ahmed
      color: darkAccent
footer_links:
  - label: Linkedin
    href: https://www.linkedin.com/in/musavvirinfo/
  - label: Résumé
    href: /s/musa-resume-2026.pdf
  - label: Iconfinder
    href: https://www.iconfinder.com/musavvir
  - label: Dribbble
    href: https://dribbble.com/musavvir
