#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for Execute cutover go-live (#26).
# Pre-NS staging: ./scripts/pre-cutover-wizard.sh (#25).
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish [headline [subtext]] — closing summary. Headline defaults to "Setup complete";
# optional subtext names async or follow-up work the wizard does not block on.
finish() {
  _clear
  local headline="${1:-Setup complete}" subtext="${2:-}"
  printf '\n%s%s  ✓ %s%s\n' "$BOLD" "$GREEN" "$headline" "$RESET"
  [[ -n "$subtext" ]] && note "$subtext"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Load pre-cutover values from .env (written by pre-cutover-wizard.sh / #25).
CF_NS_1=$(_existing CF_NS_1 || true)
CF_NS_2=$(_existing CF_NS_2 || true)
PAGES_DEV_URL=$(_existing PAGES_DEV_URL || true)

banner "musavvir.info cutover go-live (#26)"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "Assumes ./scripts/pre-cutover-wizard.sh finished (#25): CF zone, mail DNS, pages.dev smoke."
if [[ -z "$CF_NS_1" || -z "$CF_NS_2" ]]; then
  warn "CF_NS_1 / CF_NS_2 missing from $ENV_FILE."
  step "Run ./scripts/pre-cutover-wizard.sh first, or enter nameservers now."
  ask CF_NS_1 "Cloudflare nameserver 1:"
  ask CF_NS_2 "Cloudflare nameserver 2:"
  write_env CF_NS_1 "$CF_NS_1"
  write_env CF_NS_2 "$CF_NS_2"
fi
if [[ -z "$PAGES_DEV_URL" ]]; then
  ask PAGES_DEV_URL "Pages project URL (https://ss-to-gh.pages.dev):"
  write_env PAGES_DEV_URL "$PAGES_DEV_URL"
fi
note "Nameservers to set at Squarespace: $CF_NS_1, $CF_NS_2"
note "Preview URL: $PAGES_DEV_URL"
if ! PAGES_DEV_URL="$PAGES_DEV_URL" npm run pages:smoke; then
  warn "pages:smoke failed — fix deploy before go-live."
  exit 1
fi
note "pages:smoke passed."
if ! confirm "Ready for go-live? (no NS rollback — fix forward on Cloudflare only)"; then
  warn "Stopped before nameserver cutover."
  exit 1
fi

# ── Stage 2: NS cutover (go-live) ─────────────────────────────────────────
stage "Squarespace: nameserver cutover"
warn "GO-LIVE: traffic leaves Squarespace hosting."
open_url "https://account.squarespace.com/domains/managed/musavvir.info/dns/domain-nameservers"
step "DNS → Domain Nameservers (not Nameserver Registration)."
say "If the list is read-only (only USE SQUARESPACE NAMESERVERS, no trash icons):"
step "Click USE SQUARESPACE NAMESERVERS → Continue (discards stale NS — expected)."
step "Click USE CUSTOM NAMESERVERS (appears after the reset)."
step "UPDATE NAMESERVERS or add fields: $CF_NS_1 and $CF_NS_2 only."
step "Save. Re-auth if prompted; Continue if asked to disable DNSSEC."
note "DNS → DNSSEC: disable first if a toggle or DS records are present."
note "Use Safari or Firefox if Chrome hides edit controls."
if ! confirm "Both Cloudflare nameservers saved at Squarespace?"; then
  warn "NS change not confirmed — re-run from this stage."
  exit 1
fi
write_env CUTOVER_NS_CHANGED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── Stage 3: wait for zone Active ─────────────────────────────────────────
stage "Cloudflare: wait for zone Active"
say "Pages custom domains need an Active zone — do not attach while Pending."
open_url "https://dash.cloudflare.com/?to=/:account/domains/overview"
step "Find musavvir.info — Status must show Active (not Invalid nameservers)."
step "Optional CLI: dig NS musavvir.info +short — expect $CF_NS_1 and $CF_NS_2."
note "Propagation often takes minutes; allow up to 24h before retrying."
pause "Zone status is Active?"

# ── Stage 4: Pages apex custom domain ─────────────────────────────────────
stage "Pages: add apex domain"
say "Workers & Pages → ss-to-gh → Custom domains tab. Zone must already be Active."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/ss-to-gh/domains"
step "Custom domains tab → Set up a custom domain."
step "Enter musavvir.info → Continue."
step "Confirm new DNS record (CNAME @ → ss-to-gh.pages.dev) → Activate domain."
step "Let Cloudflare create the record — do not hand-add a CNAME in DNS."
warn "If you see Transfer DNS management → do not click Begin DNS transfer."
note "That loop means NS are not Active yet — return to stage 3."
pause "musavvir.info shows Active on Custom domains?"

# ── Stage 5: Pages www custom domain ──────────────────────────────────────
stage "Pages: add www domain"
say "Same Custom domains tab as stage 4 — no need to open a new tab."
step "Set up a custom domain → www.musavvir.info → Continue."
step "Confirm DNS record → Activate domain."
pause "www.musavvir.info shows Active on Custom domains?"
write_env CUTOVER_CUSTOM_DOMAINS "yes"

# ── Stage 6: Bulk Redirect www→apex ───────────────────────────────────────
stage "Bulk Redirect: www→apex"
say "Account → Delivery & performance → Bulk Redirects (Rules top, Lists bottom)."
open_url "https://dash.cloudflare.com/?to=/:account/bulk-redirects"
step "Create Bulk Redirect List — name: musavvir_www_to_apex (underscores only)."
step "Add one URL redirect. Source is locked after save — enter it correctly once."
step "Source: www.musavvir.info  (hostname only — no https://, no /* wildcard)"
note "UI may show Source as www.musavvir.info/ — trailing slash is OK."
step "Target: https://musavvir.info   Status: 301 (ignore the 307/308 tip)."
step "Edit parameters (sidebar) — check ALL four: Preserve query string,"
step "  Include subdomains, Subpath matching, Preserve path suffix."
step "Save and exit the list editor. List Status should show Active."
step "Create Bulk Redirect Rule — name: musavvir www to apex."
step "Associated List: musavvir_www_to_apex → Enabled toggle ON."
warn "Do NOT use Source https://www…/* or Target …/\${1} (that is Single Redirect syntax)."
note "List alone does nothing — rule must be Enabled. www DNS must stay Proxied."
pause "List Active with correct row; rule Enabled?"
write_env CUTOVER_WWW_REDIRECT "yes"

# ── Stage 7: verify production ────────────────────────────────────────────
stage "Verify production"
open_url "https://musavvir.info"
step "https://musavvir.info loads the Pages site with valid HTTPS."
open_url "https://www.musavvir.info/some-path?x=1"
step "www URL 301s to https://musavvir.info/some-path?x=1 (path + query kept)."
step "Terminal: dig MX musavvir.info +short — jellyfish.systems hosts."
step "Optional: curl -sI https://www.musavvir.info | grep -i location"
pause "Apex, www redirect, and mail MX all look correct?"
write_env CUTOVER_PRODUCTION_VERIFIED "yes"

# ── Stage 8: TLS hardening ──────────────────────────────────────────────────
stage "Cloudflare: TLS settings"
open_url "https://dash.cloudflare.com/?to=/:account/musavvir.info/ssl-tls/edge-certificates"
step "Always Use HTTPS → On."
step "HSTS → Enable. Max-Age: 6 months. Preload: Off. Include subDomains: Off."
step "No-Sniff Header: Off (optional — not required for cutover)."
note "Enable HSTS only after apex HTTPS is confirmed (stage 7)."
pause "Always Use HTTPS and HSTS saved?"

# ── Stage 9: cancel Squarespace website ───────────────────────────────────
stage "Squarespace: cancel website"
say "Site billing — not account.squarespace.com (that page is blank)."
warn "Cancel the website plan only — not the domain subscription."
open_url "https://musavvirinfo.squarespace.com/config/settings/billing/subscriptions"
step "Subscriptions → website plan → Cancel subscription."
step "CONTINUE through the steps (reason, feedback, confirm)."
note "UI schedules cancel at billing-cycle end (e.g. Sep 16, 2026) — stops renewal."
note "No refund after 14-day window; musavvir.info already on Cloudflare."
note "Do not cancel the domain subscription here — transfer comes in stage 11."
if ! confirm "Website subscription cancellation submitted?"; then
  warn "Website may still renew — cancel manually, then continue."
fi
write_env CUTOVER_WEBSITE_CANCELED "yes"

# ── Stage 10: unlock + auth code ──────────────────────────────────────────
stage "Squarespace: unlock + auth code"
say "Request the transfer code — do not paste it into this wizard."
warn "Avoid DNS edits at Squarespace while Porkbun transfer is pending."
open_url "https://account.squarespace.com/domains/managed/musavvir.info"
step "DOMAIN LOCK → Off (transfer window only)."
step "Send Transfer Authentication Code (or Request transfer code)."
step "Code emails to the registrant contact from no-reply@squarespace.com (≤24h)."
note "Paste the code only on Porkbun (stage 11) — never commit it to .env."
if ! confirm "Auth code requested (or already in your inbox)?"; then
  warn "Request the code before Porkbun transfer (stage 11)."
fi
write_env CUTOVER_AUTH_CODE_REQUESTED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── Stage 11: Porkbun transfer ────────────────────────────────────────────
stage "Porkbun: submit transfer"
say "Transfer page — not /account/transfer (404). Use top-nav Transfer or:"
open_url "https://porkbun.com/transfer"
step "Domain Name: musavvir.info"
step "Auth Code: paste from Squarespace email here only (not stored by wizard)."
step "WHOIS privacy + auto-renew checked → Add Transfers to Cart."
step "Cart → Continue to Billing → pay."
note ".info transfer is ~USD 22.14 — includes one year registration."
write_env CUTOVER_PORKBUN_TRANSFER_STARTED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
pause "Transfer submitted? Porkbun shows pending transfer from losing registrar?"

# ── Stage 12: monitor transfer + finish ─────────────────────────────────────
stage "Monitor Porkbun transfer (async)"
say "Go-live steps are done. This stage is a checklist — the wizard ends after you note it."
open_url "https://porkbun.com/account/transfers"
step "Status pending transfer from losing registrar is normal — wait ~5 days."
step "Check Porkbun Domain Transfers every few days until complete."
note "Optional expedite (Tucows backend): registrant inbox may get a confirm"
note "link from noreply@opensrs.email or @registrarmail.net — click if it arrives."
note "No email? Wait five business days; transfer still proceeds."
step "After Porkbun shows complete: NS should still be $CF_NS_1, $CF_NS_2."
step "Squarespace: disable domain auto-renew (domain sub ends after transfer)."
open_url "https://porkbun.com/account/domains"
pause "Monitoring plan noted?"

finish "Go-live complete" \
  "Site is on Cloudflare. Porkbun domain transfer still pending (~5–7 days) — check Domain Transfers every few days until complete."
