#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for Execute cutover go-live (#26).
# Pre-NS staging: ./scripts/pre-cutover-wizard.sh (#25).
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Load pre-cutover values from .env (written by pre-cutover-wizard.sh / #25).
CF_NS_1=$(_existing CF_NS_1 || true)
CF_NS_2=$(_existing CF_NS_2 || true)
PAGES_DEV_URL=$(_existing PAGES_DEV_URL || true)

banner "musavvir.info cutover go-live (#26)"

# ── Stage 1: preflight ────────────────────────────────────────────────────
stage "Preflight"
say "Assumes ./scripts/pre-cutover-wizard.sh finished (#25): CF zone, mail DNS, pages.dev smoke."
if [[ -z "$CF_NS_1" || -z "$CF_NS_2" ]]; then
  warn "CF_NS_1 / CF_NS_2 missing from $ENV_FILE."
  step "Run ./scripts/pre-cutover-wizard.sh first, or enter nameservers now."
  ask CF_NS_1 "Cloudflare nameserver 1:"
  ask CF_NS_2 "Cloudflare nameserver 2:"
  write_env CF_NS_1 "$CF_NS_1"
  write_env CF_NS_2 "$CF_NS_2"
fi
if [[ -z "$PAGES_DEV_URL" ]]; then
  ask PAGES_DEV_URL "Pages project URL (https://ss-to-gh.pages.dev):"
  write_env PAGES_DEV_URL "$PAGES_DEV_URL"
fi
note "Nameservers to set at Squarespace: $CF_NS_1, $CF_NS_2"
note "Preview URL: $PAGES_DEV_URL"
if ! PAGES_DEV_URL="$PAGES_DEV_URL" npm run pages:smoke; then
  warn "pages:smoke failed — fix deploy before go-live."
  exit 1
fi
note "pages:smoke passed."
if ! confirm "Ready for go-live? (no NS rollback — fix forward on Cloudflare only)"; then
  warn "Stopped before nameserver cutover."
  exit 1
fi

# ── Stage 2: NS cutover (go-live) ─────────────────────────────────────────
stage "Squarespace: nameserver cutover"
warn "GO-LIVE: traffic leaves Squarespace hosting."
open_url "https://account.squarespace.com/domains/managed/musavvir.info/dns/nameservers"
step "Open Nameservers."
step "Choose Use custom nameservers (not Squarespace defaults)."
step "Remove every Squarespace / NSONE nameserver."
step "Add: $CF_NS_1"
step "Add: $CF_NS_2"
step "Save."
if ! confirm "Both Cloudflare nameservers saved at Squarespace?"; then
  warn "NS change not confirmed — re-run from this stage."
  exit 1
fi
write_env CUTOVER_NS_CHANGED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# ── Stage 3: wait for zone Active ─────────────────────────────────────────
stage "Cloudflare: wait for zone Active"
say "Pages custom domains need an Active zone — do not attach while Pending."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/musavvir.info"
step "Overview → Status must show Active (not Pending)."
step "Optional CLI: dig NS musavvir.info +short — expect $CF_NS_1 and $CF_NS_2."
note "Propagation often takes minutes; allow up to 24h before retrying."
pause "Zone status is Active?"

# ── Stage 4: Pages apex custom domain ─────────────────────────────────────
stage "Pages: add apex domain"
say "Workers & Pages → ss-to-gh → Custom domains. Zone must already exist in this account."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/ss-to-gh/settings/custom-domains"
step "Custom domains → Set up a domain."
step "Enter musavvir.info → Continue."
step "Let Cloudflare create the DNS record — do not hand-add a CNAME."
warn "If you see Transfer DNS management → do not click Begin DNS transfer."
note "That loop means NS are not Active yet — return to stage 3."
pause "musavvir.info shows Active on Custom domains?"

# ── Stage 5: Pages www custom domain ──────────────────────────────────────
stage "Pages: add www domain"
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/ss-to-gh/settings/custom-domains"
step "Set up a domain → www.musavvir.info → Continue."
step "Accept the auto-created CNAME for www."
pause "www.musavvir.info shows Active on Custom domains?"
write_env CUTOVER_CUSTOM_DOMAINS "yes"

# ── Stage 6: Bulk Redirect www→apex ───────────────────────────────────────
stage "Bulk Redirect: www→apex"
say "ADR-0004: path and query preserved via \${1} capture group."
open_url "https://dash.cloudflare.com/?to=/:account/bulk-redirects"
step "Create Bulk Redirect List → name it musavvir-www-to-apex."
step "Or, manually add URL redirects → add one row:"
step "  Source URL:  https://www.musavvir.info/*"
step "  Target URL:  https://musavvir.info/\${1}"
step "  Status:      301"
step "Continue to Redirect Rules → Save and Deploy."
pause "Bulk Redirect rule deployed?"
write_env CUTOVER_WWW_REDIRECT "yes"

# ── Stage 7: verify production ────────────────────────────────────────────
stage "Verify production"
open_url "https://musavvir.info"
step "https://musavvir.info loads the Pages site with valid HTTPS."
open_url "https://www.musavvir.info/some-path?x=1"
step "www URL 301s to https://musavvir.info/some-path?x=1 (path + query kept)."
step "Terminal: dig MX musavvir.info +short — jellyfish.systems hosts."
step "Optional: curl -sI https://www.musavvir.info | grep -i location"
pause "Apex, www redirect, and mail MX all look correct?"
write_env CUTOVER_PRODUCTION_VERIFIED "yes"

# ── Stage 8: TLS hardening ──────────────────────────────────────────────────
stage "Cloudflare: TLS settings"
open_url "https://dash.cloudflare.com/?to=/:account/:zone/musavvir.info/ssl-tls/edge-certificates"
step "Always Use HTTPS → On."
step "HTTP Strict Transport Security (HSTS) → Enable."
step "Max-Age: ~6 months. Preload: Off. Include subDomains: Off."
note "Enable HSTS only after apex HTTPS is confirmed (stage 7)."
pause "Always Use HTTPS and HSTS saved?"

# ── Stage 9: cancel Squarespace website ───────────────────────────────────
stage "Squarespace: cancel website"
warn "Irreversible for Squarespace hosting. Cancel now — not Retain Access."
open_url "https://account.squarespace.com/settings/billing/subscriptions"
step "Find the website subscription (not the domain subscription)."
step "Cancel → immediate cancel. Do not choose Retain Access."
step "Before 16 Sep 2026 renewal (~€132) if still in that billing window."
if ! confirm "Website subscription canceled?"; then
  warn "Website may still bill — cancel manually, then continue."
fi
write_env CUTOVER_WEBSITE_CANCELED "yes"

# ── Stage 10: unlock + auth code ──────────────────────────────────────────
stage "Squarespace: unlock + auth code"
say "Start Porkbun transfer same day. Avoid DNS edits while transfer is pending."
open_url "https://account.squarespace.com/domains/managed/musavvir.info/registration"
step "Domain Lock → Off (only for the transfer window)."
step "Request transfer / auth code."
step "Code arrives by email from no-reply@squarespace.com (within 24h)."
ask_secret SS_AUTH_CODE "Paste auth/EPP code when it arrives:"
write_env SS_AUTH_CODE "$SS_AUTH_CODE"
note "Use the latest code only — a new request invalidates older codes."

# ── Stage 11: Porkbun transfer ────────────────────────────────────────────
stage "Porkbun: submit transfer"
open_url "https://porkbun.com/account/transfer"
step "Enter musavvir.info and the auth code."
step "Keep WHOIS privacy and auto-renew enabled."
step "Pay the transfer fee (~5–7 business days to complete)."
write_env CUTOVER_PORKBUN_TRANSFER_STARTED "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
pause "Transfer submitted at Porkbun?"

# ── Stage 12: Tucows confirm + finish ─────────────────────────────────────
stage "Tucows confirm + cleanup"
say "Watch the registrant inbox for the expedited-transfer link."
step "From noreply@opensrs.email or @registrarmail.net — click confirm."
step "Skipping confirm adds ~5 business days."
step "After Porkbun shows complete: NS should still be $CF_NS_1, $CF_NS_2."
step "Squarespace: turn off domain auto-renew (subscription ends after transfer)."
open_url "https://porkbun.com/account/domains"
pause "Transfer confirm handled and post-transfer cleanup done?"

finish
