#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill for www→apex 301 fix (ADR-0004 / #26).
# Lived experience (2026-09-03): Source URL is read-only after save — delete
# the legacy https://www…/* + ${1} row and add www.musavvir.info → apex with
# Edit-parameters sidebar (all four checked). Rule = Enabled toggle, not a
# separate Deploy wording. UI may show Source with a trailing slash — OK.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish [headline [subtext]] — closing summary. Headline defaults to "Setup complete";
# optional subtext names async or follow-up work the wizard does not block on.
finish() {
  _clear
  local headline="${1:-Setup complete}" subtext="${2:-}"
  printf '\n%s%s  ✓ %s%s\n' "$BOLD" "$GREEN" "$headline" "$RESET"
  [[ -n "$subtext" ]] && note "$subtext"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

banner "Fix www→apex 301 (ADR-0004)"

# ── Stage 1: DNS www proxied ──────────────────────────────────────────────
stage "DNS: www must be proxied"
say "Bulk Redirects only apply when www is Proxied (orange cloud)."
open_url "https://dash.cloudflare.com/?to=/:account/musavvir.info/dns/records"
step "Find the www row (usually CNAME → ss-to-gh.pages.dev from Pages)."
step "Proxy status = Proxied. Do not flip it to DNS only."
note "Skip inventing a second www A/CNAME — one proxied www row is enough."
pause "www is Proxied?"

# ── Stage 2: Bulk Redirect list + rule ────────────────────────────────────
stage "Bulk Redirect: www → apex"
say "Account home → Delivery & performance → Bulk Redirects."
say "Page has two blocks: Bulk Redirect Rules (top) and Bulk Redirect Lists (bottom)."
open_url "https://dash.cloudflare.com/?to=/:account/bulk-redirects"

say "── Fix the list item (bottom: Bulk Redirect Lists) ──"
step "Open list musavvir_www_to_apex (or Create Bulk Redirect List if missing)."
step "Open Edit URLs / Add URLs so you see the redirect row(s)."
warn "Source URL is read-only after save — you cannot edit it in place."
say "Wrong legacy row looks like:"
note "  Source  https://www.musavvir.info/*"
note "  Target  https://musavvir.info/\${1}"
step "Delete that row with the X, then add a new URL redirect."
step "New Source: www.musavvir.info   (type hostname only — no https://, no /*)"
note "Dashboard may display Source as www.musavvir.info/ — trailing slash is OK."
step "New Target: https://musavvir.info"
step "Status: 301 - Permanent Redirect (ignore the blue tip about 307/308)."
step "Click Edit parameters (opens a sidebar) — check ALL four:"
step "  Preserve query string"
step "  Include subdomains"
step "  Subpath matching"
step "  Preserve path suffix"
step "Save and exit (or Save, then leave Edit URLs)."
note "List Status badge should read Active when you return to Bulk Redirects."

say "── Confirm the rule (top: Bulk Redirect Rules) ──"
step "Find rule musavvir www to apex → Associated List = musavvir_www_to_apex."
step "Enabled toggle must be ON (green). Create the rule if missing."
note "If the rule already exists and is Enabled, you do not need to recreate it."
note "Wording is Enabled / Active — not always a separate Deploy button."
pause "List row fixed, list Active, rule Enabled on musavvir_www_to_apex?"

# ── Stage 3: verify 301 ───────────────────────────────────────────────────
stage "Verify 301"
say "Confirm in a second terminal (this wizard stays open):"
note "  curl -sI https://www.musavvir.info/ | grep -iE '^(HTTP|location)'"
note "  curl -sI 'https://www.musavvir.info/some-path?x=1' | grep -iE '^(HTTP|location)'"
note "Expect HTTP/2 301 and Location: https://musavvir.info/... (path + query kept)."
open_url "https://www.musavvir.info/"
step "Browser address bar should become https://musavvir.info/ (www dropped)."
if ! confirm "curl shows 301 with Location to https://musavvir.info/?"; then
  warn "Re-check: wrong /* row gone, Source www.musavvir.info, all four params, rule Enabled."
  exit 1
fi
write_env CUTOVER_WWW_REDIRECT "yes-verified-$(date -u +%Y-%m-%dT%H:%M:%SZ)"

finish "www→apex 301 fixed" \
  "Canonical hostname policy (ADR-0004) restored. Safe to close #26 after this verifies."
