#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish [headline [subtext]] — closing summary. Headline defaults to "Setup complete";
# optional subtext names async or follow-up work the wizard does not block on.
finish() {
  _clear
  local headline="${1:-Setup complete}" subtext="${2:-}"
  printf '\n%s%s  ✓ %s%s\n' "$BOLD" "$GREEN" "$headline" "$RESET"
  [[ -n "$subtext" ]] && note "$subtext"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "GoatCounter site musavvir-info (#42)"

# ── Stage 1: Sign in via an existing sibling site ─────────────────────────
stage "Sign in"
say "Use the existing GoatCounter account (same family as musavvir-fyi / musavvir-work)."
say "Do not create a brand-new GoatCounter.com signup."
open_url "https://musavvir-fyi.goatcounter.com"
step "Sign in if prompted (same users/login as other sites on this account)."
step "If musavvir-fyi is wrong, open https://musavvir-work.goatcounter.com instead."
pause "Logged into the existing GoatCounter account?"

# ── Stage 2: Create site code musavvir-info ───────────────────────────────
stage "Create site musavvir-info"
say "New site under this account — separate from musavvir-fyi / musavvir-work."
open_url "https://musavvir-fyi.goatcounter.com/settings/sites"
step "Settings → Sites (admin tab)."
step "In the Code field under the site list, type: musavvir-info"
step "Click Add new."
note "You will access the new site at https://musavvir-info.goatcounter.com"
note "Current site settings are copied on create, then independent — stage 4 re-checks."
pause "Sites list shows musavvir-info?"

# ── Stage 3: Canonical link domain ────────────────────────────────────────
stage "Your site = musavvir.info"
say "Set the display/link domain to the Canonical hostname (apex, not www)."
say "www is fine via the existing apex 301; do not rely on counting on www HTML."
open_url "https://musavvir-info.goatcounter.com/settings/main"
step "Open the musavvir-info dashboard if you are still on another site."
step "Settings → Settings (first tab)."
step "Site settings → Your site: enter musavvir.info  (no https://, no www)."
step "Save (bottom of the form)."
note "GoatCounter does not block other hosts server-side; the embed ticket gates on apex."
pause "Your site is musavvir.info and settings are saved?"

# ── Stage 4: Individual pageviews off ─────────────────────────────────────
stage "Individual pageviews off"
say "Leave individual pageview storage off (GoatCounter default; privacy + disk)."
open_url "https://musavvir-info.goatcounter.com/settings/main#section-collect"
step "Same Settings page → Data collection fieldset."
step "Confirm Individual pageviews is unchecked."
step "If it is checked (copied from a sibling), uncheck it and Save."
pause "Individual pageviews is off?"

# ── Stage 5: Self-noise — clear Ignore IPs; prefer #toggle-goatcounter ────
stage "Self-noise (clear Ignore IPs + hash toggle)"
say "New sites copy settings from the sibling you created from — including Ignore IPs."
say "An Ignore IPs entry makes count return 202 but drop the hit (dashboard stays empty)."
say "Leave Ignore IPs empty until after the first live hit verifies. Prefer #toggle-goatcounter."
open_url "https://musavvir-info.goatcounter.com/settings/main#section-tracking"
step "Settings → Tracking → Ignore IPs."
step "Clear every IP in the list (including any copied from a sibling)."
step "Do NOT click Add your current IP yet. Save if you changed anything."
say "Browser opt-out after the embed ships (no dashboard change required):"
step "Visit https://musavvir.info#toggle-goatcounter — popup confirms; F5 if you typed the hash."
note "Ignore IPs = every request from those addresses (easy to blank the dashboard)."
note "Hash toggle = this browser only. Add Ignore IPs later only if you still need it."
pause "Ignore IPs is empty and you know #toggle-goatcounter?"

# ── Stage 6: Record count endpoint for the embed ticket ───────────────────
stage "Record count endpoint"
say "Non-secret handoff for Embed Visit counter (#43). No GitHub secrets."
open_url "https://musavvir-info.goatcounter.com"
step "Confirm the dashboard loads for site code musavvir-info."
note "Count endpoint is always https://<code>.goatcounter.com/count"
ask GOATCOUNTER_SITE_CODE "Site code (expect musavvir-info):"
ask GOATCOUNTER_COUNT_URL "Paste count URL (expect https://musavvir-info.goatcounter.com/count):"
if [[ "$GOATCOUNTER_SITE_CODE" != "musavvir-info" ]]; then
  warn "Site code is not musavvir-info — ADR-0010 and #43 expect that exact code."
  if ! confirm "Continue with $GOATCOUNTER_SITE_CODE anyway?"; then
    warn "Fix the site code in GoatCounter, then re-run this stage."
    exit 1
  fi
fi
write_env GOATCOUNTER_SITE_CODE "$GOATCOUNTER_SITE_CODE"
write_env GOATCOUNTER_COUNT_URL "$GOATCOUNTER_COUNT_URL"

finish "GoatCounter site ready" \
  "Next: Embed Visit counter (#43) using GOATCOUNTER_COUNT_URL from $ENV_FILE."
